import "./globals.css";
import '@/config/env.server'
import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import AsideMenu from "../components/aside-menu";
import Header from '@/components/header';
import { getAppToken } from "@/lib/auth";
import LoginButton from '@/components/login-button';

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const token = await getAppToken();
  if (!token) {
    return <html lang="en" suppressHydrationWarning>
      <body className={`${geistSans.variable} ${geistMono.variable} antialiased h-screen w-screen grid place-content-center`}>
        <LoginButton />
      </body>
    </html>
  }

  return (
    <html lang="en" suppressHydrationWarning>
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <div id="layout" className="relative sm:h-screen p-1 md:p-2 gap-1 md:gap-2">
          <header className="[grid-area:header] bg-neutral-50 p-2 rounded-lg border border-neutral-100">
            <Header />
          </header>
          <aside className="[grid-area:aside] h-[calc(100vh-80px)] bg-neutral-50 p-2 rounded-lg border border-neutral-100">
            <AsideMenu />
          </aside>

          <main
            className="[grid-area:main] rounded-lg bg-neutral-50 p-2 overflow-y-auto w-full border border-neutral-100"
          >
            {children}
          </main>

        </div>
      </body>
    </html>
  );
}
